import cv2
image = cv2.imread('all.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
hsv = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
lab = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
cv2.imwrite('all_gray.jpg',gray)
cv2.imwrite('all_hsv.jpg',hsv)
cv2.imwrite('all_lab.jpg',lab)
cv2.imshow('gray',gray)
cv2.imshow('hsv',hsv)
cv2.imshow('lab',lab)
cv2.waitKey(0)
cv2.destroyAllWindows()